-- =============================================
-- 265Stream - Storage Buckets & Policies
-- Migration 003: Storage Configuration
-- Run this in the Supabase SQL Editor AFTER migrations 001 & 002
-- =============================================

-- ============================================
-- 1. CREATE STORAGE BUCKETS
-- ============================================

-- Audio files bucket (PRIVATE - access via signed URLs only)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'audio-files',
  'audio-files',
  FALSE,  -- PRIVATE: no public access
  52428800,  -- 50MB max file size
  ARRAY['audio/mpeg', 'audio/wav', 'audio/flac', 'audio/aac', 'audio/ogg', 'audio/mp4', 'audio/x-m4a']
);

-- Cover images bucket (PRIVATE by default, served via signed URLs)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'cover-images',
  'cover-images',
  FALSE,  -- PRIVATE: controlled access
  5242880,  -- 5MB max file size
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
);


-- ============================================
-- 2. STORAGE POLICIES FOR AUDIO-FILES BUCKET
-- ============================================

-- Artists can upload audio files to their own folder
CREATE POLICY "audio_upload_artist"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'audio-files'
    AND auth.uid() IS NOT NULL
    AND (storage.foldername(name))[1] = auth.uid()::text
    AND EXISTS (
      SELECT 1 FROM public.artist_profiles
      WHERE user_id = auth.uid() AND status = 'approved'
    )
  );

-- Artists can update/replace their own audio files
CREATE POLICY "audio_update_artist"
  ON storage.objects FOR UPDATE
  USING (
    bucket_id = 'audio-files'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Artists can delete their own audio files
CREATE POLICY "audio_delete_artist"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'audio-files'
    AND (
      (storage.foldername(name))[1] = auth.uid()::text
      OR public.is_admin(auth.uid())
    )
  );

-- Audio files can be read only by:
-- 1. The artist who uploaded them
-- 2. Users who have purchased the song
-- 3. Admins
-- NOTE: In practice, audio access is controlled via signed URLs
-- generated by the backend after purchase verification.
-- This policy provides an additional security layer.
CREATE POLICY "audio_select_authorized"
  ON storage.objects FOR SELECT
  USING (
    bucket_id = 'audio-files'
    AND (
      -- Artist who owns the file
      (storage.foldername(name))[1] = auth.uid()::text
      -- Admin access
      OR public.is_admin(auth.uid())
      -- Purchased access (checked via backend signed URLs primarily)
      OR EXISTS (
        SELECT 1 FROM public.songs s
        JOIN public.purchases p ON p.song_id = s.id
        WHERE s.audio_storage_path = name
          AND p.buyer_id = auth.uid()
          AND p.status = 'completed'
      )
    )
  );


-- ============================================
-- 3. STORAGE POLICIES FOR COVER-IMAGES BUCKET
-- ============================================

-- Artists can upload cover images to their own folder
CREATE POLICY "cover_upload_artist"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'cover-images'
    AND auth.uid() IS NOT NULL
    AND (storage.foldername(name))[1] = auth.uid()::text
    AND EXISTS (
      SELECT 1 FROM public.artist_profiles
      WHERE user_id = auth.uid() AND status = 'approved'
    )
  );

-- Artists can update their own cover images
CREATE POLICY "cover_update_artist"
  ON storage.objects FOR UPDATE
  USING (
    bucket_id = 'cover-images'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Artists can delete their own cover images
CREATE POLICY "cover_delete_artist"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'cover-images'
    AND (
      (storage.foldername(name))[1] = auth.uid()::text
      OR public.is_admin(auth.uid())
    )
  );

-- Cover images are viewable by anyone (for browsing the catalog)
-- They're still served via signed URLs for access control,
-- but we allow SELECT for all authenticated users
CREATE POLICY "cover_select_public"
  ON storage.objects FOR SELECT
  USING (
    bucket_id = 'cover-images'
  );
